[build]
target = "wasm32-unknown-unknown"

[package]
authors = ["Sixshaman <shaman1234@gmail.com>"]
edition = "2021"
name = "stafra_wgpu"
version = "0.1.2"
resolver = "2"

[dependencies.wasm-bindgen]
git = "https://github.com/Sixshaman/wasm-bindgen.git"

[dependencies.web-sys]
git = "https://github.com/Sixshaman/wasm-bindgen.git"
features = ["Document", "Navigator", "Node", "NodeList", "Gpu", "GpuAdapter", "GpuAddressMode", "GpuBindGroup", "GpuBindGroupDescriptor", "GpuBindGroupEntry", "GpuBindGroupLayout", "GpuBindGroupLayoutDescriptor", "GpuBindGroupLayoutEntry", "GpuBlendFactor", "GpuBlendOperation", "GpuBuffer", "GpuBufferBinding", "GpuBufferDescriptor", "GpuBufferUsage", "GpuCanvasContext", "GpuColorDict", "GpuColorWrite", "GpuCommandBuffer", "GpuCommandBufferDescriptor", "GpuCommandEncoder", "GpuCommandEncoderDescriptor", "GpuCompareFunction", "GpuCompilationInfo", "GpuCompilationMessage", "GpuCompilationMessageType", "GpuComputePassDescriptor", "GpuComputePassEncoder", "GpuComputePipeline", "GpuComputePipelineDescriptor", "GpuCullMode", "GpuDevice", "GpuDeviceDescriptor", "GpuDeviceLostInfo", "GpuErrorFilter", "GpuExtent3dDict", "GpuFeatureName", "GpuFilterMode", "GpuFrontFace", "GpuIndexFormat", "GpuLoadOp", "GpuMapMode", "GpuObjectDescriptorBase", "GpuOrigin2dDict", "GpuOrigin3dDict", "GpuOutOfMemoryError", "GpuPipelineDescriptorBase", "GpuPipelineLayout", "GpuPipelineLayoutDescriptor", "GpuPipelineStatisticName", "GpuPowerPreference", "GpuPrimitiveTopology", "GpuQuerySet", "GpuQuerySetDescriptor", "GpuQueryType", "GpuQueue", "GpuRenderBundle", "GpuRenderBundleDescriptor", "GpuRenderBundleEncoder", "GpuRenderBundleEncoderDescriptor", "GpuRenderPassDescriptor", "GpuRenderPassEncoder", "GpuRenderPipeline", "GpuRenderPipelineDescriptor", "GpuRequestAdapterOptions", "GpuSampler", "GpuSamplerDescriptor", "GpuShaderModule", "GpuShaderModuleDescriptor", "GpuShaderStage", "GpuStencilOperation", "GpuStoreOp", "GpuTexture", "GpuTextureAspect", "GpuTextureDescriptor", "GpuTextureDimension", "GpuTextureFormat", "GpuTextureUsage", "GpuTextureView", "GpuTextureViewDescriptor", "GpuTextureViewDimension", "GpuUncapturedErrorEvent", "GpuUncapturedErrorEventInit", "GpuValidationError", "GpuVertexFormat", "HtmlAnchorElement", "HtmlCanvasElement", "HtmlButtonElement", "HtmlSelectElement", "HtmlOptionElement", "HtmlOptionsCollection", "HtmlInputElement", "HtmlImageElement", "ImageData", "FileList", "File", "FileReader", "CanvasRenderingContext2d", "Window", "VideoPixelFormat", "VideoFrameBufferInit"]

[dependencies.js-sys]
git = "https://github.com/Sixshaman/wasm-bindgen.git"

[dependencies.wasm-bindgen-futures]
git = "https://github.com/Sixshaman/wasm-bindgen.git"

[dependencies]
wgpu = {git = "https://github.com/Sixshaman/wgpu.git", branch = "compat"}
winit = {git = "https://github.com/Sixshaman/winit.git", branch = "compat"}
console_log = {git = "https://github.com/Sixshaman/console_log.git", branch = "compat"}
console_error_panic_hook = { git = "https://github.com/Sixshaman/console_error_panic_hook.git", branch = "compat"}
image = "0.23.14"
cgmath = "0.17"
env_logger = "0.8.3"
log = "0.4"
futures = "0.3.14"

[[bin]]
name = "stafra_native"
path = "src/main.rs"

[lib]
name = "stafra"
path = "src/lib.rs"
crate-type = ["cdylib"]