[package]
authors = ["Sixshaman <shaman1234@gmail.com>"]
edition = "2018"
name = "stafra_wgpu"
version = "0.1.0"

[dependencies]
image = "0.23"
winit = "0.22"
cgmath = "0.17"
env_logger = "0.8.3"
log = "0.4"
futures = "0.3.14"
wasm-bindgen-futures = "0.4.23"
js-sys = "0.3.50"
wgpu = "0.9.0"
wasm-bindgen = "0.2.74"
web-sys = {version = "0.3.50", features = ["Document", "Navigator", "Node", "NodeList", "Gpu", "GpuAdapter", "GpuAdapterFeatures", "GpuAddressMode", "GpuBindGroup", "GpuBindGroupDescriptor", "GpuBindGroupEntry", "GpuBindGroupLayout", "GpuBindGroupLayoutDescriptor", "GpuBindGroupLayoutEntry", "GpuBlendFactor", "GpuBlendOperation", "GpuBuffer", "GpuBufferBinding", "GpuBufferDescriptor", "GpuBufferUsage", "GpuCanvasContext", "GpuColorDict", "GpuColorWrite", "GpuCommandBuffer", "GpuCommandBufferDescriptor", "GpuCommandEncoder", "GpuCommandEncoderDescriptor", "GpuCompareFunction", "GpuCompilationInfo", "GpuCompilationMessage", "GpuCompilationMessageType", "GpuComputePassDescriptor", "GpuComputePassEncoder", "GpuComputePipeline", "GpuComputePipelineDescriptor", "GpuCullMode", "GpuDevice", "GpuDeviceDescriptor", "GpuDeviceLostInfo", "GpuErrorFilter", "GpuExtent3dDict", "GpuFeatureName", "GpuFilterMode", "GpuFrontFace", "GpuIndexFormat", "GpuInputStepMode", "GpuLoadOp", "GpuMapMode", "GpuObjectDescriptorBase", "GpuOrigin2dDict", "GpuOrigin3dDict", "GpuOutOfMemoryError", "GpuPipelineDescriptorBase", "GpuPipelineLayout", "GpuPipelineLayoutDescriptor", "GpuPipelineStatisticName", "GpuPowerPreference", "GpuPrimitiveTopology", "GpuQuerySet", "GpuQuerySetDescriptor", "GpuQueryType", "GpuQueue", "GpuRenderBundle", "GpuRenderBundleDescriptor", "GpuRenderBundleEncoder", "GpuRenderBundleEncoderDescriptor", "GpuRenderPassDescriptor", "GpuRenderPassEncoder", "GpuRenderPipeline", "GpuRenderPipelineDescriptor", "GpuRequestAdapterOptions", "GpuSampler", "GpuSamplerDescriptor", "GpuShaderModule", "GpuShaderModuleDescriptor", "GpuShaderStage", "GpuStencilOperation", "GpuStoreOp", "GpuSwapChain", "GpuSwapChainDescriptor", "GpuTexture", "GpuTextureAspect", "GpuTextureDescriptor", "GpuTextureDimension", "GpuTextureFormat", "GpuTextureUsage", "GpuTextureView", "GpuTextureViewDescriptor", "GpuTextureViewDimension", "GpuUncapturedErrorEvent", "GpuUncapturedErrorEventInit", "GpuValidationError", "GpuVertexFormat", "HtmlAnchorElement", "HtmlCanvasElement", "HtmlButtonElement", "ImageData", "CanvasRenderingContext2d", "Window"]}

[lib]
name = "stafra"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stafra_native"
path = "src/main.rs"