name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-bindgen-action@v0.1.0
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install wasm-bindgen
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
    - name: Create deploy folder
      run: mkdir -p static
    - name: Copy HTML
      uses: canastro/copy-file-action@master
      with:
        source: "src/stafra.html"
        target: "static/stafra.html"
    - name: Copy CSS
      uses: canastro/copy-file-action@master
      with:
        source: "src/stafra.css"
        target: "static/stafra.css"
