name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-bindgen-action@v0.1.0
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install wasm-bindgen
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
    - name: Create deploy folder
      run: mkdir -p static
    - name: Copy HTML
      uses: canastro/copy-file-action@master
      with:
        source: "src/stafra.html"
        target: "static/stafra.html"
    - name: Copy CSS
      uses: canastro/copy-file-action@master
      with:
        source: "src/stafra.css"
        target: "static/stafra.css"
    - name: Build
      id: build_stafra
      run:
        RUSTFLAGS=--cfg=web_sys_unstable_apis CARGO_TARGET_DIR="target" cargo build --verbose --lib --release --target wasm32-unknown-unknown --message-format=json
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"

    - uses: actions/checkout@v1

    - name: Fetch action
      id: pl
      uses: Rishabh510/Path-lister-action@master
      with:
        path: ".github/"
        type: ".yml"

    - name: Output results
      run: |
        echo "Found ${{ steps.build_stafra.outputs.path_count }} file(s) with this extension:"
        for i in ${{ steps.build_stafra.outputs.paths }}; do
        echo $i
        done
        
    - name: Pack the wasm files
      run:
        wasm-bindgen --target web --out-name stafra --out-dir static target/wasm32-unknown-unknown/release/stafra.wasm
    - name: Run tests
      run: 
        RUSTFLAGS=--cfg=web_sys_unstable_apis CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner cargo test --verbose --target wasm32-unknown-unknown
