name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Wasm-Bindgen
      uses: jetli/wasm-bindgen-action@v0.1.0
      with:
        version: 0.2.81
    - name: Create deploy folder
      run: mkdir -p ${GITHUB_WORKSPACE}/static
    - name: Copy HTML
      uses: canastro/copy-file-action@master
      with:
        source: "src/stafra.html"
        target: "static/stafra.html"
    - name: Copy CSS
      uses: canastro/copy-file-action@master
      with:
        source: "src/stafra.css"
        target: "static/stafra.css"
    - name: Build
      id: build_stafra
      run:
        RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --verbose --lib --release --target wasm32-unknown-unknown
    - name: List contents part 2
      run: |
           for file in ${GITHUB_WORKSPACE}/*; do
           echo "${file##*/}"
           done
    - name: Pack the wasm files
      run:
        wasm-bindgen --target web --out-name stafra --out-dir static ${GITHUB_WORKSPACE}/target/wasm32-unknown-unknown/release/stafra.wasm
    - name: Run tests
      run: 
        RUSTFLAGS=--cfg=web_sys_unstable_apis CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner cargo test --verbose --target wasm32-unknown-unknown
